-- Admins table with email + password hash
create table if not exists public."Admins" (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public."Admins" enable row level security;

-- Simple policies: allow nothing by default (service role API will access)
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='Admins' and policyname='Admins no select') then
    create policy "Admins no select" on public."Admins" for select to authenticated using (false);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='Admins' and policyname='Admins no insert') then
    create policy "Admins no insert" on public."Admins" for insert to authenticated with check (false);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='Admins' and policyname='Admins no delete') then
    create policy "Admins no delete" on public."Admins" for delete to authenticated using (false);
  end if;
end $$;


